# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: a82ff5b734f9a88d30a21a7ca01cdc95b30df8afd178132f005ab9c6a4ffc11b67992cf7b1bb11460dc061e4b652d51a8a88a2adcb2d7f7306cc62c88fee5445

test:
  secret_key_base: 64b4c8cc6c61de629335b854a2b4697322e1571371daf6ee3f66672eaa81270460f0cd7bd92a41a81405c859558d2d465c9d1a38ebf998d7c840fff4e7fd77bf

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
